config/routes.rb
SocialProject::Application.routes.draw do

  resources :users do
    resource :friend_circle
    resources :friend_circle_memberships, :as => :friendships
    resources :posts
  end

  resource :password_reset, only: [:new, :show, :create, :edit, :update]
  resource :session

end

app/controllers/password_reset_controller.rb
class PasswordResetsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:email])

    if @user
     reset_token = SecureRandom.urlsafe_base64(16)

      @user.reset_token = reset_token
      @user.save!

      msg = PasswordMailer.password_reset(@user)
      msg.deliver!
    else
      flash.now[:errors] = ["Cannot find user!"]
      render :new
    end
  end

  def show

  end

  def edit
    @user = User.new
  end

  def update
    user = User.find_by_reset_token(params[:reset_token])
    if user
      user.password = params[:password]
      user.reset_token = nil
      user.save!
      login!(user)

      redirect_to user_url(user)
    else
      flash.now[:errors] = ["Invalid reset token!"]
      redirect_to new_password_reset_url
    end
  end

end

app/helpers/password_reset_helper.rb
module PasswordResetHelper
end

app/views/password_resets/edit.html.erb
<h1>Password Reset</h1>

<form action="<%= edit_password_reset_url %>" method="POST">
  <input type='hidden' name='_method' value='PUT'>
  <input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'>

  <input type='hiden' name='user[reset_token]' value='<%= params[:reset_token] %>'>

  <input type='password' name='user[password]'>

  <input type='submit' value='Reset Password'>
</form>

app/views/password_resets/new.html.erb
<h1>Password Reset</h1>

<form action='<%= password_reset_url %>' method='POST'>
  <label>
    Email
    <input type='email' name='email'>
  </label>
  <button>Submit</button>
</form>