config/routes.rb
SocialProject::Application.routes.draw do

  resources :users do
    resource :friend_circle
    resources :friend_circle_memberships, :as => :friendships
    resources :posts
  end

  resource :password_reset, only: [:new, :show, :create, :edit, :update]
  resource :session

end

app/models/friend_circle_membership.rb
# == Schema Information
#
# Table name: friend_circle_memberships
#
#  id         :integer          not null, primary key
#  friend_id  :integer
#  circle_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class FriendCircleMembership < ActiveRecord::Base
  validates :friend_id, :circle_id, :presence => true, :numericality => true


  belongs_to(
  :circle,
  :class_name => "FriendCircleMembership",
  :foreign_key => :friend_id,
  :primary_key => :id
  )

  belongs_to(
  :friend,
  :class_name => "User",
  :foreign_key => :friend_id,
  :primary_key => :id
  )
end

app/controllers/friend_circle_memberships_controller.rb
class FriendCircleMembershipsController < ApplicationController

  def new
    @friend_membership = FriendCircleMembership.new
    @exclusion = current_user.friends.map(&:id)
    @exclusion << current_user.id
    @users = User.where("id not in (?)", @exclusion)
  end

  def create
    @circle = current_user.friend_circle

    params[:friend][:friend_ids].each do |friend_id|
      @circle.friendships.build(:friend_id => friend_id.to_i)
    end

    if @circle.save
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @circle.errors.full_messages
      @circle.friendships.each do |friendship|
        flash.now[:errors] << friendship.errors.full_messages
      end
      render :new
    end

  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

#  friend[friend_ids][]
end

app/helpers/friend_circle_memberships_helper.rb
module FriendCircleMembershipsHelper
end

app/views/friend_circle_memberships/new.html.erb
<h1>Friendship Circle</h1>

<%= current_user.email %>


<form action='<%= user_friendships_url %>' method='POST'>
  <input type='hidden' name='authenticity_token'
          value='<%= form_authenticity_token %>'>

  <% @users.each do |user| %>

    <label>
      <%= user.email %>
      <input type="checkbox" name="friend[friend_ids][]"
              value='<%= user.id %>'>
    </label>
  <% end %>
  <button>Make Friends!!!!</button>
</form>