config/routes.rb
SocialProject::Application.routes.draw do

  resources :users do
    resource :friend_circle
    resources :friend_circle_memberships, :as => :friendships
    resources :posts
  end

  resource :password_reset, only: [:new, :show, :create, :edit, :update]
  resource :session

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :string(255)      not null
#  author_id  :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :body, length: {minimum: 10, maximum: 200}
  validates :author_id, :body, presence: true

  has_many(
    :post_shares,
    :class_name => 'PostShare',
    :foreign_key => :post_id,
    :primary_key => :id,
    :dependent => :destroy
  )

  has_many(
    :links,
    :dependent => :destroy
  )


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
  end

  def new
    @post = Post.new(author_id: params[:user_id].to_i)
    @circles = current_user.friend_circles
    3.times {@post.links.build}
  end

  def create


  end

  def edit
  end

  def update
  end

  def detroy
  end

  private
  def post_params
    params.permit(:link)
  end

  def link_params
    params.permit(:links => [:content]).require(:links).values
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/new.html.erb
<h1>Create a Post </h1>

<form action="<%= user_posts_url %>" method="POST">
  <input type='hidden' name='authenticity_token'
    value='<%= form_authenticity_token %>'>

    <label>Select a circle:</label>

    Select Your Circles:
    <% @circles.each do |circle| %>
      <label>
        <%= circle.id %>
        <input type="checkbox" name="post[circle_ids][]"
                value='<%= circle.id %>'>
      </label>
    <% end %>

    <label>Body:
      <textarea name="post[body]"></textarea>
    </label>

    <% @post.links.each_with_index do |link, idx| %>
      <label>
        Link <%= idx %>
        <input type='text' name='links[<%= idx %>][content]' />
      </label>
      <br />
    <% end %>

    <button>submit</button>
</form>